Added update verify and create functions
tic-oss/wda-server pull request #35
Opened 2023-08-11 04:54 UTC by Sri-Harsha06

2023-08-11 05:20 UTC, craxkumar requested changes

2023-08-11 05:20 UTC, craxkumar commented on designer/router.js
> +    router.get('/user/:project_id',wda.verifyproject);
Follow Camel 🐪 casing for method name 
verifyProject

2023-08-11 05:20 UTC, craxkumar commented on designer/router.js
> +    router.post('/create',wda.createBlueprint);
Router can be called as 
/blueprints/create

2023-08-11 05:20 UTC, craxkumar commented on designer/controller.js
> +        if(userId == uniqueResult.user_id){
No need to send the string called Yes or No u can simple use the http status 
So when it return 200 the http_status will be OK when it returns 204 the status will be NO_CONTENT u can either use http code or status no need to send the string externally 
Give it a try

2023-08-11 05:20 UTC, craxkumar commented on designer/controller.js
> +  // return res.status(204).send("No");
Remove this commented line if not required, please

2023-08-12 17:43 UTC, craxkumar requested changes

2023-08-12 17:43 UTC, craxkumar commented on designer/router.js
> +    router.post('/update/:project_id',wda.updateBlueprint);
so that i missed to point out 
but please change this url to 
/blueprints/update

2023-08-13 04:59 UTC, craxkumar requested changes
Update the routers as disccused!

2023-08-14 05:45 UTC, craxkumar approved these changes
Review OK!

2023-08-14 06:03 UTC, rohithteja-cmi requested changes
Please format the code added as part of this PR

2023-08-14 10:03 UTC, rohithteja-cmi approved these changes

2023-08-14 10:03 UTC, merged